# Configuration for the connection string to MongoDB database
spring:
  main:
    allow-circular-references: true

  data:
    mongodb:
      # Configure database location
      host: localhost
      port: 27017
      database: Space-X-demo

      # Configure credential
      username: aseAdmin
      password: test
      authentication-database: admin

      # Configure Database Operation,
      # allow creating index automatically from the code
      auto-index-creation: true

      #enable the usage of Spring Data Mongo Repository
      repositories:
        enabled: true